apiVersion: v1
kind: Service
metadata:
  name: vets-service
  labels:
    app: vets-service
spec:
  ports:
    - name: http
      port: 8083
      targetPort: 8083
  selector:
    app: vets-service
  type: ClusterIP