version: '2'

services:
  config-server:
    image: quay.io/phagen/spring-petclinic-config-server
    container_name: config-server
    environment:
      - OTEL_SERVICENAME="ph-config-server"
      - JAVA_TOOL_OPTIONS="-javaagent:/opt/otel/splunk-otel-javaagent-all.jar -Dsplunk.profiler.call.stack.interval=1000ms -Dsplunk.profiler.include.internal.stacks=false -Dsplunk.profiler.cpu.data.format=pprof-gzip-base64"
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://127.0.0.0:4317"        
    mem_limit: 512M
    ports:
     - 8888:8888

  discovery-server:
    image: quay.io/phagen/spring-petclinic-discovery-server
    container_name: discovery-server
    environment:
      - OTEL_SERVICENAME="ph-discovery-server"
      - JAVA_TOOL_OPTIONS="-javaagent:/opt/otel/splunk-otel-javaagent-all.jar -Dsplunk.profiler.call.stack.interval=1000ms -Dsplunk.profiler.include.internal.stacks=false -Dsplunk.profiler.cpu.data.format=pprof-gzip-base64"
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://127.0.0.0:4317"        
    mem_limit: 512M
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8761:8761

  customers-service:
    image: quay.io/phagen/spring-petclinic-customers-service
    container_name: customers-service
    environment:
      - OTEL_SERVICENAME="ph-customers-service"
      - JAVA_TOOL_OPTIONS="-javaagent:/opt/otel/splunk-otel-javaagent-all.jar -Dsplunk.profiler.call.stack.interval=1000ms -Dsplunk.profiler.include.internal.stacks=false -Dsplunk.profiler.cpu.data.format=pprof-gzip-base64"
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://127.0.0.0:4317"        
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
    - 8081:8081

  visits-service:
    image: quay.io/phagen/spring-petclinic-visits-service
    container_name: visits-service
    environment:
      - OTEL_SERVICENAME="ph-visits-service"
      - JAVA_TOOL_OPTIONS="-javaagent:/opt/otel/splunk-otel-javaagent-all.jar -Dsplunk.profiler.call.stack.interval=1000ms -Dsplunk.profiler.include.internal.stacks=false -Dsplunk.profiler.cpu.data.format=pprof-gzip-base64"
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://127.0.0.0:4317" 
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8082:8082

  vets-service:
    image: quay.io/phagen/spring-petclinic-vets-service
    container_name: vets-service
    environment:
      - OTEL_SERVICENAME="ph-vets-service"
      - JAVA_TOOL_OPTIONS="-javaagent:/opt/otel/splunk-otel-javaagent-all.jar -Dsplunk.profiler.call.stack.interval=1000ms -Dsplunk.profiler.include.internal.stacks=false -Dsplunk.profiler.cpu.data.format=pprof-gzip-base64"
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://127.0.0.0:4317" 
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8083:8083

  api-gateway:
    image: quay.io/phagen/spring-petclinic-api-gateway
    container_name: api-gateway
    mem_limit: 512M
    environment:
      - OTEL_SERVICENAME="ph-api-gateway"
      - JAVA_TOOL_OPTIONS="-javaagent:/opt/otel/splunk-otel-javaagent-all.jar -Dsplunk.profiler.call.stack.interval=1000ms -Dsplunk.profiler.include.internal.stacks=false -Dsplunk.profiler.cpu.data.format=pprof-gzip-base64"
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://127.0.0.0:4317" 
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 8080:8080

  admin-server:
    image: quay.io/phagen/spring-petclinic-admin-server 
    container_name: admin-server
    environment:
      - OTEL_SERVICENAME="ph-admin-server"
      - JAVA_TOOL_OPTIONS="-javaagent:/opt/otel/splunk-otel-javaagent-all.jar -Dsplunk.profiler.call.stack.interval=1000ms -Dsplunk.profiler.include.internal.stacks=false -Dsplunk.profiler.cpu.data.format=pprof-gzip-base64"
      - OTEL_EXPORTER_OTLP_ENDPOINT="http://127.0.0.0:4317" 
    mem_limit: 512M
    depends_on:
     - config-server
     - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
    ports:
     - 9090:9090

