spring:
  application:
    name: vets-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cache:
    cache-names: vets
  profiles:
    active: production

---

spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888

---

spring:
  datasource:
    url: jdbc:mysql://database-service:3306/vetsdb
    username: ${DB-USERNAME}
    password: ${DB-PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
