apiVersion: v1
kind: Service
metadata:
  name: tracing
  labels:
    app: tracing
spec:
  ports:
    - name: http
      port: 9411
      targetPort: 9411
  selector:
    app: tracing
  type: ClusterIP