ingress:
  enabled: true
  className: "nginx"
  host: "preview.dev"
  pathType: Prefix

  # Nếu bạn không cần rewrite đường dẫn, thì bỏ luôn annotation này
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: / # chỉ dùng nếu muốn strip prefix

  rules:
    - path: /
      service: api-gateway
      port: 8080

    - path: /admin-server
      service: admin-server
      port: 9090

    - path: /config-server
      service: config-server
      port: 8888

    - path: /discovery-server
      service: discovery-server
      port: 8761

    - path: /api/genai
      service: genai-service
      port: 8084

    - path: /api/customer
      service: customers-service
      port: 8081

    - path: /api/vet
      service: vets-service
      port: 8083

    - path: /api/visit
      service: visits-service
      port: 8082

    - path: /api/gateway
      service: api-gateway
      port: 8080
