apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: grafana-server-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    name: grafana
  triggers:
    - type: prometheus
      metadata:
        serverAddress: "http://prometheus-server.default.svc.cluster.local:9090"
        metricName: "http_requests_total"
        threshold: "100"
