apiVersion: v1
kind: Service
metadata:
  name: grafana-server
  labels:
    app: grafana-server
spec:
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: grafana-server
  type: ClusterIP