name: Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Azure CLI Login
      run: |
        echo "Logging into Azure using Service Principal..."
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

        echo "Setting subscription..."
        az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}

        echo "Getting AKS credentials..."
        az aks get-credentials --resource-group ${{ secrets.AKS_RESOURCE_GROUP }} --name ${{ secrets.AKS_CLUSTER_NAME }}

        echo "Listing AKS nodes..."
        kubectl get nodes
