name: Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      run: |
        az login --service-principal \
          --username ${{ secrets.AZURE_CLIENT_ID }} \
          --password ${{ secrets.AZURE_CLIENT_SECRET }} \
          --tenant ${{ secrets.AZURE_TENANT_ID }}

    - name: Get AKS Credentials
      run: |
        az aks get-credentials \
          --resource-group petclinic-resource-group \
          --name petclinic-aks-cluster \
          --overwrite-existing

    - name: Deploy to Kubernetes
      run: kubectl apply -f k8s/ --recursive
